// Copyright (C) 2025 Soud Al Kharusi
// SPDX-License-Identifier: AGPL-3.0-or-later

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/gestures.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../utils/theme_utils.dart';

class AboutScreen extends StatefulWidget {
  const AboutScreen({Key? key}) : super(key: key);

  @override
  State<AboutScreen> createState() => _AboutScreenState();
}

class _AboutScreenState extends State<AboutScreen> {
  final _supabase = Supabase.instance.client;
  int? _totalQuestions;
  int? _totalResponses;
  bool _isLoadingStats = true;

  // YouTube video URL
  static const String youtubeVideoUrl = 'https://www.youtube.com/watch?v=kr3VyJ-Dr5U';

  // Text content sections (declared as static const so they can be used in a const context).
  static const String aboutText =
      "> read(the_room) — RTR — is a litmus test of human sentiment, Earth's vibe check.\n\n"
      "Our mission is to anonymously capture, summarize, and display responses to questions posed by members of the public on a local, national, and global scale.\n";

  static const String premiseText =
      "Ever wonder how everyone else really feels about something, or feel like your views are not fairly represented in conventional media or by your representatives? You aren't alone.\n\n"
      "In today's world, vast amounts of data are collected about us, yet access to this data is often limited to profit-driven corporations. We are routinely shaped by algorithms designed to monetize our attention rather than empower our decision-making. It's time for a change.\n\n"
      "RTR aims to democratize data by aggregating anonymous contributions from individuals like you, making the results transparent and accessible to all.\n\n"
      "Our ethos is transparency, openness, and trust. Our promise to you is simple: we will only collect what is necessary to make this platform work for you and nothing more.";

  static const String guidelinesText =
      "Help us create a respectful, thought-provoking, and fun environment.\n\n"
      "If you encounter any offensive or problematic content, please report it via the report button which is available at the bottom of each question.\n\n"
      "We aim to foster a welcoming community where everyone is able to express their thoughts and browse topics that matter to them. To support that, please tag your questions apropriately and use the NSFW toggle when addressing an adult audience.\n\n"
      "We have zero tolerance for doxxing, harassment, abuse, incitement of violence, and illegal content. If you encounter any of this, please report the question immediately and write to: ";

  static const String guidelinesEmailText = "support@readtheroom.site";

  static const String disclaimerText =
      "The content of RTR is generated by users and does not reflect the views or beliefs of the platforms's creators or administrators. We do not take responsibility for any content posted by the users of RTR.\n\n"
      "Our automated moderation system relies on user reports, please help us by reporting any problematic material you see.\n\n"
      "By using this platform, you agree not to hold the creators or administrators liable for any damages arising from the use of RTR.";

  static const String aboutUsText =
      "> read(the_room) started as a web app, originally developed in November 2023 by graduate students at McGill University.\n\n"
      "Since its inception, many have contributed to RTR's development. We are grateful to all of our technical and non-technical contributors.";

  // Active Members
  static const List<Map<String, String>> activeMembers = [
    {"name": "Soud Al Kharusi", "url": "https://soudkharusi.com"},
    {"name": "Janay Fox", "url": "https://janayafox.wixsite.com/my-site"},
  ];

  // Past Contributors
  static const List<Map<String, String>> pastContributors = [
    {
      "name": "Brendon McGuinness",
      "url": "https://www.linkedin.com/in/brendon-mcguinness-095096135/?originalSubdomain=ca"
    },
    {"name": "Nicolas Gastellu", "url": "https://github.com/ngastellu"},
    {"name": "Shayan Hajhashemi", "url": "https://github.com/shayshay42"},
    {"name": "Naila Al Kharusi", "url": "https://linktr.ee/nooshwellness"},
    {"name": "Olivier Eydt", "url": "https://github.com/olieydt"},
    {"name": "Hussein Al Abri", "url": "https://zidhuss.tech/about/"},
    {"name": "Chris Ross", "url": "https://x.com/chrispyross?lang=en"},
  ];

  @override
  void initState() {
    super.initState();
    _loadDatabaseStats();
  }

  Future<void> _loadDatabaseStats() async {
    try {
      // Fetch total questions count
      final questionsResponse = await _supabase
          .from('questions')
          .select('id')
          .count(CountOption.exact);
      
      // Fetch total responses count
      final responsesResponse = await _supabase
          .from('responses')
          .select('id')
          .count(CountOption.exact);
      
      if (mounted) {
        setState(() {
          _totalQuestions = questionsResponse.count;
          _totalResponses = responsesResponse.count;
          _isLoadingStats = false;
        });
      }
    } catch (e) {
      print('Error loading database stats: $e');
      if (mounted) {
        setState(() {
          _isLoadingStats = false;
        });
      }
    }
  }

  String _formatCount(int count) {
    if (count >= 1000000) {
      return '${(count / 1000000).toStringAsFixed(1)}M';
    } else if (count >= 1000) {
      return '${(count / 1000).toStringAsFixed(1)}K';
    } else {
      return count.toString();
    }
  }

  // Helper function to launch a URL.
  Future<void> _launchURL(String url) async {
    final Uri uri = Uri.parse(url);
    if (!await launchUrl(uri, mode: LaunchMode.externalApplication)) {
      throw 'Could not launch $url';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('About')),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ExpansionTile(
                title: const Text("ABOUT", style: TextStyle(fontWeight: FontWeight.bold)),
                initiallyExpanded: true,
                children: [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text(aboutText, style: Theme.of(context).textTheme.bodyMedium),
                  ),
                ],
              ),
              ExpansionTile(
                title: const Text("COMMUNITY GUIDELINES", style: TextStyle(fontWeight: FontWeight.bold)),
                children: [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(guidelinesText, style: Theme.of(context).textTheme.bodyMedium),
                        TextButton(
                          onPressed: () async {
                            await Clipboard.setData(ClipboardData(text: guidelinesEmailText));
                            if (context.mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(
                                  content: Text('Email copied to clipboard'),
                                  duration: Duration(seconds: 2),
                                  backgroundColor: Colors.teal,
                                ),
                              );
                            }
                          },
                          style: TextButton.styleFrom(
                            padding: EdgeInsets.zero,
                            minimumSize: Size(0, 0),
                            alignment: Alignment.centerLeft,
                          ),
                          child: Text(
                            guidelinesEmailText,
                            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                              color: Colors.teal,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                        SizedBox(height: 16),
                        RichText(
                          text: TextSpan(
                            style: Theme.of(context).textTheme.bodyMedium,
                            children: [
                              TextSpan(text: 'See our full '),
                              TextSpan(
                                text: 'Terms of Service',
                                style: TextStyle(
                                  color: Theme.of(context).primaryColor,
                                  fontWeight: FontWeight.bold,
                                ),
                                recognizer: TapGestureRecognizer()
                                  ..onTap = () => launchUrl(Uri.parse('https://readtheroom.site/terms/')),
                              ),
                              TextSpan(text: ' and '),
                              TextSpan(
                                text: 'Privacy Policy',
                                style: TextStyle(
                                  color: Theme.of(context).primaryColor,
                                  fontWeight: FontWeight.bold,
                                ),
                                recognizer: TapGestureRecognizer()
                                  ..onTap = () => launchUrl(Uri.parse('https://readtheroom.site/privacy')),
                              ),
                              TextSpan(text: '.'),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              ExpansionTile(
                title: const Text("PREMISE & CONCEPT", style: TextStyle(fontWeight: FontWeight.bold)),
                children: [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text(premiseText, style: Theme.of(context).textTheme.bodyMedium),
                  ),
                ],
              ),
              ExpansionTile(
                title: const Text("DISCLAIMER", style: TextStyle(fontWeight: FontWeight.bold)),
                children: [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text(disclaimerText, style: Theme.of(context).textTheme.bodyMedium),
                  ),
                ],
              ),
              ExpansionTile(
                title: const Text("ABOUT US", style: TextStyle(fontWeight: FontWeight.bold)),
                children: [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Text(aboutUsText, style: Theme.of(context).textTheme.bodyMedium),
                  ),
                  const SizedBox(height: 16),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 8.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(
                          "Current Team",
                          style: Theme.of(context).textTheme.titleMedium
                        ),
                      ],
                    ),
                  ),
                  ...activeMembers.map((contributor) {
                    return ListTile(
                      title: Text(contributor['name']!),
                      onTap: () => _launchURL(contributor['url']!),
                      dense: true,
                    );
                  }),
                  const SizedBox(height: 12),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 8.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(
                          "Past Contributors",
                          style: Theme.of(context).textTheme.titleMedium
                        ),
                        SizedBox(width: 6),
                        Icon(
                          Icons.favorite,
                          color: Theme.of(context).textTheme.titleMedium?.color,
                          size: 16,
                        ),
                      ],
                    ),
                  ),
                  ...pastContributors.map((contributor) {
                    return ListTile(
                      title: Text(contributor['name']!),
                      onTap: () => _launchURL(contributor['url']!),
                      dense: true,
                    );
                  }),
                ],
              ),
              const SizedBox(height: 24),
              const Text("Podcast overview of the RTR vision", 
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              const SizedBox(height: 16),
              
              // YouTube video card with thumbnail and play button
              Card(
                elevation: 4,
                child: InkWell(
                  onTap: () => _launchURL(youtubeVideoUrl),
                  borderRadius: BorderRadius.circular(8),
                  child: AspectRatio(
                    aspectRatio: 16 / 9, // Standard YouTube video aspect ratio
                    child: Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(8),
                        image: const DecorationImage(
                          image: NetworkImage('https://img.youtube.com/vi/kr3VyJ-Dr5U/maxresdefault.jpg'),
                          fit: BoxFit.cover,
                          onError: null, // Handle errors gracefully
                        ),
                        // Fallback gradient in case image fails to load
                        gradient: const LinearGradient(
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                          colors: [
                            Color(0xFFEF5350), // Red shade
                            Color(0xFFE53935), // Darker red shade
                          ],
                        ),
                      ),
                      child: Container(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(8),
                          // Dark overlay for better text/button visibility
                          gradient: LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: [
                              Colors.transparent,
                              Colors.black.withOpacity(0.3),
                            ],
                          ),
                        ),
                        child: Stack(
                          alignment: Alignment.center,
                          children: [
                            // Play button icon
                            Container(
                              padding: const EdgeInsets.all(12),
                              decoration: BoxDecoration(
                                color: Colors.red,
                                shape: BoxShape.circle,
                                boxShadow: ThemeUtils.getFloatingShadow(context),
                              ),
                              child: const Icon(
                                Icons.play_arrow,
                                size: 32,
                                color: Colors.white,
                              ),
                            ),
                            // YouTube logo and text at bottom
                            Positioned(
                              bottom: 12,
                              left: 12,
                              right: 12,
                              child: Row(
                                children: [
                                  const FaIcon(
                                    FontAwesomeIcons.youtube,
                                    color: Colors.white,
                                    size: 20,
                                  ),
                                  const SizedBox(width: 8),
                                  const Expanded(
                                    child: Text(
                                      'RTR Audio Overview',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 14,
                                        fontWeight: FontWeight.bold,
                                        shadows: [
                                          Shadow(
                                            offset: Offset(0, 1),
                                            blurRadius: 2,
                                            color: Colors.black54,
                                          ),
                                        ],
                                      ),
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ),
                                  const Icon(
                                    Icons.open_in_new,
                                    color: Colors.white,
                                    size: 16,
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              
              const SizedBox(height: 8),
      
              
              const SizedBox(height: 24),
              
              // Database Statistics Section
              Padding(
                padding: EdgeInsets.symmetric(horizontal: 4),
                child: Text(
                  'Platform Stats',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              SizedBox(height: 12),
              
              // Total Questions Card
              Card(
                margin: EdgeInsets.only(bottom: 8),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12.0),
                  side: BorderSide(
                    color: Theme.of(context).brightness == Brightness.dark 
                        ? Colors.white 
                        : Colors.grey,
                    width: 1.0,
                  ),
                ),
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: Row(
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: BoxDecoration(
                          color: Theme.of(context).primaryColor.withOpacity(0.1),
                          shape: BoxShape.circle,
                        ),
                        child: Icon(
                          Icons.quiz,
                          color: Theme.of(context).primaryColor,
                          size: 24,
                        ),
                      ),
                      SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Question Tally',
                              style: Theme.of(context).textTheme.titleMedium?.copyWith(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            SizedBox(height: 4),
                            Text(
                              'Total number of questions',
                              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                color: Colors.grey[600],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                        decoration: BoxDecoration(
                          color: Theme.of(context).primaryColor,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: _isLoadingStats
                            ? SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                                ),
                              )
                            : Text(
                                _totalQuestions != null ? _formatCount(_totalQuestions!) : '0',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 18,
                                ),
                              ),
                      ),
                    ],
                  ),
                ),
              ),
              
              // Total Responses Card
              Card(
                margin: EdgeInsets.only(bottom: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12.0),
                  side: BorderSide(
                    color: Theme.of(context).brightness == Brightness.dark 
                        ? Colors.white 
                        : Colors.grey,
                    width: 1.0,
                  ),
                ),
                child: Padding(
                  padding: EdgeInsets.all(16),
                  child: Row(
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: BoxDecoration(
                          color: Theme.of(context).primaryColor.withOpacity(0.1),
                          shape: BoxShape.circle,
                        ),
                        child: Icon(
                          Icons.people,
                          color: Theme.of(context).primaryColor,
                          size: 24,
                        ),
                      ),
                      SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Response Tally',
                              style: Theme.of(context).textTheme.titleMedium?.copyWith(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            SizedBox(height: 4),
                            Text(
                              'Total number of responses',
                              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                color: Colors.grey[600],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                        decoration: BoxDecoration(
                          color: Theme.of(context).primaryColor,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: _isLoadingStats
                            ? SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                                ),
                              )
                            : Text(
                                _totalResponses != null ? _formatCount(_totalResponses!) : '0',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 18,
                                ),
                              ),
                      ),
                    ],
                  ),
                ),
              ),
              
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    'Support us by following our socials',
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: Colors.grey,
                      fontWeight: FontWeight.bold,
                      fontSize: 11,
                    ),
                  ),
                  SizedBox(width: 4),
                  Icon(
                    Icons.favorite,
                    color: Colors.grey,
                    size: 12,
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  IconButton(
                    icon: const FaIcon(FontAwesomeIcons.instagram, size: 24),
                    onPressed: () => _launchURL('https://www.instagram.com/readtheroom.site'),
                    tooltip: 'Instagram',
                  ),
                  const SizedBox(width: 8),
                  IconButton(
                    icon: const FaIcon(FontAwesomeIcons.bluesky, size: 24),
                    onPressed: () => _launchURL('https://bsky.app/profile/read-theroom.bsky.social'),
                    tooltip: 'Bluesky',
                  ),
                  const SizedBox(width: 8),
                  IconButton(
                    icon: const FaIcon(FontAwesomeIcons.youtube, size: 24),
                    onPressed: () => _launchURL('https://www.youtube.com/@readtheroom-w8w'),
                    tooltip: 'YouTube',
                  ),
                  const SizedBox(width: 8),
                  IconButton(
                    icon: const FaIcon(FontAwesomeIcons.reddit, size: 24),
                    onPressed: () => _launchURL('https://www.reddit.com/r/readtheroom/'),
                    tooltip: 'Reddit',
                  ),
                ],
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }
}
