-- Lists ORGANIC questions whose prompt collides with the seed bank.
-- Zero rows = clear to seed. Any rows = tell Claude, the bank entry gets swapped.
SELECT prompt, author_id, created_at
FROM questions
WHERE NOT is_seeded AND lower(prompt) IN (
    'does a straw have one hole or two?',
    'pineapple belongs on pizza.',
    'when do you start eating at a group meal?',
    'cereal is a soup.',
    'how full should a suitcase be?',
    'you should make your bed every morning.',
    'milk or cereal first?',
    'people can genuinely change.',
    'what''s the best pizza topping?',
    'money can buy happiness.',
    'how do you like your eggs?',
    'it''s rude to be more than five minutes late.',
    'which meal is the most important?',
    'you should tell a friend if their partner is cheating.',
    'what''s the ideal number of close friends?',
    'everyone is a little bit psychic.',
    'window or aisle seat?',
    'free will is an illusion.',
    'how early do you get to the airport?',
    'it''s fine to re-gift a present.',
    'what''s the worst chore?',
    'you should always finish a book you start.',
    'best way to spend a day off?',
    'talking to yourself out loud is healthy.',
    'coffee or tea?',
    'the best day of the week is saturday.',
    'crunchy or smooth peanut butter?',
    'long-distance relationships are worth it.',
    'what time should the day start?',
    'it''s okay to keep a secret from your best friend.',
    'shower in the morning or at night?',
    'first impressions are usually right.',
    'which season is best?',
    'you are the same person you were ten years ago.',
    'beach or mountains?',
    'sleeping in on weekends is a good use of time.',
    'how do you watch a series?',
    'everyone lies at least once a day.',
    'what do you do with the bread crust?',
    'pets understand more than we think.',
    'how spicy do you like your food?',
    'it''s okay to cry in public.',
    'best comfort food?',
    'some things happen for a reason.',
    'what''s your texting punctuation style?',
    'silence is more powerful than words.',
    'how many alarms do you set?',
    'you should reply to texts within a day.',
    'what''s the best way to say goodbye?',
    'it''s fine to eat dessert before dinner.',
    'where''s your phone at night?',
    'nostalgia does more harm than good.',
    'what''s your default walking speed?',
    'a messy desk means a creative mind.',
    'how do you organize a bookshelf?',
    'it''s okay to ghost a bad date.',
    'best weather to sleep in?',
    'everyone should learn to cook at least one meal well.',
    'how do you handle a buffet?',
    'the book is always better than the movie.',
    'what''s your ringer situation?',
    'you can be friends with an ex.',
    'best way to relax?',
    'it''s okay to lie to protect someone''s feelings.',
    'ideal nap length?',
    'growing up is mostly a loss.',
    'where''s the best place to read a book?',
    'cold weather is better than hot weather.',
    'which sense would you want heightened?',
    'you should say ''i love you'' first if you feel it.',
    'if you could instantly master one skill?',
    'time moves faster as you get older.',
    'what superpower would you pick?',
    'it''s okay to eat alone at a restaurant.',
    'would you rather talk to animals or speak every human language?',
    'people are basically good.',
    'if you could live in any era, when?',
    'dogs are better than cats.',
    'which would you rather lose for a year?',
    'it''s rude to look at your phone during a meal with others.',
    'if you could keep only one, which?',
    'a promise is a promise, no matter what.',
    'which animal would be the rudest if it could talk?',
    'everyone has a book in them.',
    'would you rather be 10 minutes late or 20 minutes early?',
    'it''s better to have loved and lost than never to have loved.',
    'if you had to eat one cuisine forever?',
    'you should forgive but not forget.',
    'would you rather read minds or predict the future?',
    'small talk is worth it.',
    'which fictional place would you visit?',
    'it''s okay to leave a party without saying goodbye.',
    'if you could have dinner with anyone?',
    'handwritten letters are worth the effort.',
    'would you rather never age or never get sick?',
    'you should follow your gut over the facts.',
    'would you rather explore the ocean or space?',
    'being busy is a choice.',
    'if you could freeze time, when would you use it?',
    'the early bird really does get the worm.',
    'which would you rather have unlimited?',
    'it''s fine to wear the same outfit two days in a row.',
    'would you rather know how you die or when?',
    'you should keep your promises to yourself.',
    'pick your ideal home.',
    'regret is a useful feeling.',
    'would you rather have a rewind or a pause button for life?',
    'everyone deserves a second chance.',
    'fluent in any language overnight, which?',
    'it''s okay to skip breakfast.',
    'which do you value most in a friend?',
    'you can love someone and not like them.',
    'what makes a house feel like home?',
    'most arguments aren''t worth having.',
    'what do you notice first about someone?',
    'a good apology never includes the word ''but''.',
    'best way to meet new people?',
    'you should travel alone at least once.',
    'how do you feel about surprise parties?',
    'it''s fine to have no close friends.',
    'best gift to give?',
    'home is a place, not a feeling.',
    'how do you apologize?',
    'you should always keep the receipt.',
    'someone tells a story you''ve already heard. you?',
    'loneliness and being alone are different things.',
    'what''s your love language?',
    'it''s okay to outgrow your friends.',
    'how do you handle conflict?',
    'the middle seat should get both armrests.',
    'what breaks the ice best?',
    'you should learn a second language.',
    'worst way to be broken up with?',
    'it''s rude to recline your seat on a plane.',
    'at a party where you know no one, you find the?',
    'everyone is the main character of their own story.',
    'how long do you wait to text back?',
    'you should keep your options open.',
    'ideal group size for a dinner?',
    'vacations are more stressful than relaxing.',
    'how do you remember names?',
    'it''s okay to not have a life plan.',
    'what''s the best age to be?',
    'your name shapes who you become.',
    'what would your younger self be most surprised by?',
    'you should trust people until they give you a reason not to.',
    'what do you want to be remembered for?',
    'being right is less important than being kind.',
    'do you think in words or pictures?',
    'it''s fine to cancel plans last minute if you''re tired.',
    'hardest part of growing up?',
    'everyone should keep a journal.',
    'which fear feels the most universal?',
    'you should say what you mean, even if it stings.',
    'where do you do your best thinking?',
    'the past is better left in the past.',
    'what''s your relationship with the past?',
    'a good night''s sleep fixes most problems.',
    'what would you tell your future self?',
    'you should never read someone''s diary.',
    'what matters most in a life?',
    'comfort zones are underrated.',
    'when you can''t sleep, what''s on your mind?',
    'it''s fine to talk during a movie.',
    'best measure of a life well lived?',
    'you should give up your seat for someone who needs it.',
    'if you could ask the universe one question?',
    'everyone is a little afraid of the dark.',
    'what''s the most human trait?',
    'it''s okay to not want kids.',
    'is time real or made up?',
    'you are your own harshest critic.',
    'which came first?',
    'the window seat is the best seat.',
    'what''s the best invention ever?',
    'you should keep your resolutions private.',
    'most overrated technology?',
    'it''s rude to show up empty-handed.',
    'how many browser tabs are open right now?',
    'deep down, everyone wants to be famous.',
    'how do you feel about voice assistants?',
    'you should quit while you''re ahead.',
    'where''s your phone battery usually at?',
    'it''s okay to enjoy being alone on your birthday.',
    'how do you feel about self-driving cars?',
    'first love is the strongest.',
    'worst part of modern phones?',
    'you should always answer a call from family.',
    'how often do you check your phone?',
    'boredom is good for you.',
    'what''s the best use of ai?',
    'you should never go to bed angry.',
    'how do you feel about apps tracking you?',
    'everyone romanticizes the past.',
    'how''s your screen time?',
    'it''s okay to pretend you didn''t see someone you know.',
    'physical books or e-readers?',
    'a stranger''s opinion matters less than a friend''s.',
    'how do you navigate a new city?',
    'you should let a call go to voicemail if you''re not ready.',
    'where do you keep your passwords?',
    'overthinking has ruined more than it''s saved.',
    'what''s your notification style?',
    'it''s fine to keep a mess as long as you know where things are.',
    'what would you save first in a fire?',
    'you should always hear both sides before judging.',
    'win a fortune tomorrow. first move?',
    'some people are just born lucky.',
    'stranded on an island, one item?',
    'it''s okay to reread the same book many times.',
    'if you could relive one day, which kind?',
    'you should keep a little mystery in every relationship.',
    '24 hours left. how do you spend it?',
    'your gut knows before your head does.',
    'you find a wallet full of cash. you?',
    'it''s rude to reply to a long message with just ''k''.',
    'a genie grants three wishes. your first?',
    'everyone should experience living alone at least once.',
    'swap lives for a day with?',
    'a good playlist can fix a bad day.',
    'you can teleport anywhere right now. where?',
    'it''s okay to cry at a movie in a theater.',
    'if you could delete one thing from existence?',
    'you never really know anyone completely.',
    'what would you do with an extra hour a day?',
    'the grass is greener where you water it.',
    'give a talk tomorrow, on what?',
    'it''s fine to keep your camera off on video calls.',
    'any animal as a loyal companion?',
    'you should say yes more than you say no.',
    'if money didn''t exist, what would you do all day?',
    'everyone has a price.',
    'which small win makes your whole day?',
    'shoes should come off at the front door.',
    'what''s the best sound?',
    'you should sleep on big decisions.',
    'what''s the best smell?',
    'arriving ten minutes late to a casual meetup is fine.',
    'most satisfying thing to do?',
    'it''s fine to eat the same meal every day.',
    'worst small inconvenience?',
    'you should let people change your mind.',
    'what''s your comfort rewatch?',
    'most people are lonelier than they let on.',
    'how do you feel about mornings?',
    'you should tip for a takeaway coffee.',
    'what''s the ideal weekend?',
    'leaving a party without saying goodbye is perfectly fine.',
    'your default mode at a party?',
    'you should tell people how you really feel more often.',
    'best way to unwind after a hard day?',
    'everyone is faking it a little.',
    'what''s your junk-drawer situation?',
    'it''s fine to eat a full meal on public transport.',
    'how do you feel about karaoke?',
    'you should keep the last slice for someone else.',
    'best midnight snack?',
    'silence in a friendship can be comfortable.',
    'what''s your dancing style?',
    'it''s rude to play music out loud in public without headphones.',
    'how do you feel about board games?',
    'you should always keep a book within reach.',
    'what kind of traveler are you?',
    'the best conversations happen after midnight.',
    'best part of a trip?',
    'you should always bring something when invited to someone''s home.',
    'what souvenir do you bring back?',
    'reclining your seat on a plane is your right.',
    'how do you pack for a trip?',
    'everyone secretly likes a compliment they didn''t earn.',
    'ideal vacation pace?',
    'it''s fine to keep to yourself at a party.',
    'road trip or flight?',
    'you should always taste your food before adding salt.',
    'worst part of travel?',
    'you should stand on the right so people can pass on an escalator.',
    'best travel companion?',
    'it''s okay to keep old text messages forever.',
    'how do you handle the bill at a restaurant?',
    'you should protect your mornings.',
    'how does your group decide where to eat?',
    'nobody is completely honest on a first date.',
    'best part of a meal?',
    'it''s fine to wear pajamas all day.',
    'how do you feel about leftovers?',
    'you should thank the driver when you get off the bus.',
    'what''s your grocery-shopping style?',
    'sending a voice message instead of typing is considerate.',
    'how do you cook?',
    'it''s fine to reply to work messages after hours.',
    'hardest food to eat politely?',
    'you should always let someone merge in traffic.',
    'what do you do with the last bite?',
    'being underestimated is an advantage.',
    'sweet or savory breakfast?',
    'it''s fine to keep a secret talent hidden.',
    'how do you feel about food touching on a plate?',
    'you should call more than you text.',
    'best kind of restaurant?',
    'you should learn some of the local language before visiting a country.',
    'which chore do you secretly enjoy?',
    'haggling over a price is just part of shopping.',
    'how do you make a big decision?',
    'it''s rude to arrive to a dinner exactly on time.',
    'what''s your relationship with clutter?',
    'you should learn to be alone before you commit to someone.',
    'how do you feel about being the center of attention?',
    'splitting the bill evenly is the fairest way.',
    'your default answer to ''how are you''?',
    'cancelling plans by text at the last minute is acceptable.',
    'when you''re stressed, you?',
    'you should call your parents at least once a week.',
    'what kind of listener are you?',
    'it''s fine to talk to your plants.',
    'how do you take a compliment?',
    'the perfect day would be spent doing nothing.',
    'your biggest time-waster?',
    'it''s okay to reinvent yourself completely.',
    'how do you feel about being wrong?',
    'it''s okay to ask someone how much they earn.',
    'what motivates you most?',
    'memories are more valuable than photographs.',
    'how do you recharge?',
    'it''s fine to skip the small talk and go straight to the deep stuff.',
    'your morning-alarm reality?',
    'taking a phone call on speaker in public is rude.',
    'which do you trust more?',
    'a hug is a normal greeting for someone you just met.',
    'best kind of saturday night?',
    'you should let yourself be a beginner at something new.',
    'how do you keep in touch with old friends?',
    'you should always finish a drink your host poured you.',
    'hardest word to say?',
    'it''s okay to have a favorite sibling.',
    'your default gift-wrapping?',
    'you should always finish what''s on your plate.',
    'how do you feel about small talk with strangers?',
    'a little bit of jealousy is healthy in a relationship.',
    'what kind of note-taker are you?',
    'it''s fine to keep your goals to yourself until they happen.',
    'a song you love comes on. you?',
    'you should walk on the outside of the sidewalk.',
    'what''s your umbrella policy?',
    'being the youngest in the room is a good feeling.',
    'how do you feel about change?',
    'you should take your hat off indoors.',
    'best thing to do on a rainy day?',
    'you should always give a stranger the benefit of the doubt.',
    'how do you eat a chocolate bar with segments?',
    'doing nothing on purpose is a skill worth having.',
    'correct way to hang toilet paper?',
    'it''s fine to keep a bit of chaos in your life.',
    'what''s the first thing you do when you wake up?',
    'leaving someone "on read" is rude.',
    'how do you feel about spoilers?',
    'everyone would time-travel to the past if they could.',
    'what kind of texter are you?',
    'it''s okay to root for the villain sometimes.',
    'how do you eat popcorn?',
    'you should always give the window seat to a kid.',
    'which is worse?',
    'a birthday is worth making a fuss over.',
    'how do you feel about your handwriting?',
    'it''s fine to keep a friendship that only exists online.',
    'best way to fall asleep?'
);
