-- Generated by scripts/seed_qotd_bank.py — initial QOTD bank seed
-- 78 questions; country_code=US, author_id=NULL (anonymous)
-- Run once in the Supabase SQL editor. Re-running aborts on the
-- sentinel guard below instead of double-seeding.
-- Every question writes its question_options rows: one per choice for
-- multiple_choice, and exactly two for approval_rating naming the
-- slider ends (sort_order 0 = low, 1 = high).

BEGIN;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM questions WHERE is_seeded AND prompt = 'Do you take your shoes off when you get home?') THEN
    RAISE EXCEPTION 'seed_qotd_bank: sentinel prompt already present — bank appears seeded; aborting';
  END IF;
END $$;

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you take your shoes off when you get home?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('Sometimes', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you wash rice before cooking it?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('Sometimes', 1), ('Never', 2), ('Don''t cook rice', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Where do you keep eggs?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Fridge', 0), ('Counter', 1), ('Depends', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you sleep with a top sheet?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No, just a duvet', 1), ('What''s a top sheet?', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How do you dry laundry?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Dryer', 0), ('Indoor rack', 1), ('Outdoor line', 2), ('Mix', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you drink tap water at home?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Straight from the tap', 0), ('Filtered', 1), ('Bottled only', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you brush your teeth before or after breakfast?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Before', 0), ('After', 1), ('Both', 2), ('Skip breakfast', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you wet your toothbrush before the toothpaste?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Before', 0), ('After', 1), ('Both', 2), ('Never', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Which utensil do you use most at home?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Fork', 0), ('Spoon', 1), ('Chopsticks', 2), ('Hands', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How do you eat pizza?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Hands', 0), ('Knife and fork', 1), ('Depends on the pizza', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you drink hot drinks on a hot day?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Happily', 0), ('Only iced', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you sleep with the window open?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('Summer only', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you iron your clothes?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Weekly', 0), ('Rarely', 1), ('Never', 2), ('Someone else does', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Toilet paper: fold or scrunch?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Fold', 0), ('Scrunch', 1), ('Wrap', 2), ('Mostly bidet', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you turn off the shower while soaping up?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you knock before entering a family member''s room?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('Sometimes', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Someone sneezes: do you say "bless you" or your language''s equivalent?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Even to strangers', 0), ('Only to people I know', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Food falls on the floor. Do you eat it?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('5-second rule', 0), ('Depends on the floor', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you talk to yourself out loud when alone?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Often', 0), ('Sometimes', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('With friends, where''s your phone?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Face down', 0), ('Face up', 1), ('In pocket or bag', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('What''s the first thing you do when you get home?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Change clothes', 0), ('Wash hands', 1), ('Eat', 2), ('Lie down', 3), ('Phone', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('If you could only have one every day: bath or shower?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Bath', 0), ('Shower', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you wear socks in bed?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('Only when cold', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('At a friend''s place, do you take your shoes off without being asked?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('If others do', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Do you thank the bus driver when getting off?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Always', 0), ('Sometimes', 1), ('Never', 2), ('Don''t take buses', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How do you wash dishes?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Dishwasher', 0), ('By hand under running water', 1), ('By hand in a filled sink', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever called in sick when you weren''t?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Never', 0), ('Once or twice', 1), ('Regularly', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever re-gifted a present?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Never', 0), ('Once', 1), ('Often', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever sent a message about someone to that person by mistake?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('Almost', 1), ('No', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ghosted anyone in the last year?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you looked up an ex online in the past year?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1), ('No exes', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('When did you last cry?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Today', 0), ('This week', 1), ('This month', 2), ('This year', 3), ('Longer ago', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever cried at work or school?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever lied about your age?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Said younger', 0), ('Said older', 1), ('Both', 2), ('Never', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Is there a friend you secretly don''t like?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever read someone''s messages without permission?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever quit a job with nothing lined up?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1), ('Never had a job', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Are you still friends with any exes?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1), ('No exes', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Have you ever pretended not to see someone you know in public?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Often', 0), ('Once or twice', 1), ('Never', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How did you meet your most recent partner?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('App', 0), ('Friends', 1), ('School or work', 2), ('Family introduction', 3), ('Out and about', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('On a first date, who should pay?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Whoever asked', 0), ('Split it', 1), ('The man', 2), ('Whoever earns more', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you let your family set you up with someone?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('Maybe', 1), ('No', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Should couples combine their finances?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Fully', 0), ('Partly', 1), ('Keep separate', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('When should you meet a partner''s parents?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Within 3 months', 0), ('3–12 months', 1), ('After a year', 2), ('Only once engaged', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you move countries for a partner?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('Maybe', 1), ('No', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you date someone who doesn''t share your first language?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('Maybe', 1), ('No', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('At what age did (or will) you move out of your parents'' home?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Under 18', 0), ('18–21', 1), ('22–25', 2), ('26–30', 3), ('30+', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Adult children should financially support their parents.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Grandparents should live with their children''s family.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('You should greet everyone when you walk into a small shop.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Calling someone without texting first is rude.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Not rude', 0), ('Rude', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Kids should call adult family friends by their first names.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Passengers should clap when the plane lands.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Speaking a language others at the table don''t understand is rude.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Not rude', 0), ('Rude', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Tipping should be abolished.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Keep tipping', 0), ('Abolish it', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('You should stand up when an older person enters the room.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Strangers should say hello when passing on a quiet street.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Disagree', 0), ('Agree', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('What time do you eat dinner on a weekday?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Before 6pm', 0), ('6–7pm', 1), ('7–8pm', 2), ('8–9pm', 3), ('After 9pm', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How late counts as "late" for a casual meetup?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('5 minutes', 0), ('15 minutes', 1), ('30 minutes', 2), ('An hour or more', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How many uses before you wash a bath towel?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('1', 0), ('2–3', 1), ('4–7', 2), ('8+', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How long is your usual shower?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Under 5 min', 0), ('5–10 min', 1), ('10–20 min', 2), ('20+ min', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('What''s your home''s indoor temperature in winter?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Under 18°C (64°F)', 0), ('18–20°C (64–68°F)', 1), ('21–23°C (70–73°F)', 2), ('24°C+ (75°F+)', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How much phone screen time did you have yesterday?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Under 2h', 0), ('2–4h', 1), ('4–6h', 2), ('6h+', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How many people live in your household, including you?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('1', 0), ('2', 1), ('3–4', 2), ('5–6', 3), ('7+', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How many hours did you work last week?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('0', 0), ('1–20', 1), ('21–40', 2), ('41–50', 3), ('50+', 4)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('How long do you keep a toothbrush?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Under 3 months', 0), ('3–6 months', 1), ('6–12 months', 2), ('Over a year', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather only eat your country''s food forever, or never eat it again?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Only my country''s food', 0), ('Never again', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather speak every language fluently, or play every instrument?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Every language', 0), ('Every instrument', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather have free flights for life, or free rent for life?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Free flights', 0), ('Free rent', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather live 100 years in the past, or 100 years in the future?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('The past', 0), ('The future', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you give up your smartphone for a year for $10,000?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Yes', 0), ('No', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather have a personal chef, or a personal driver?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Personal chef', 0), ('Personal driver', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather live abroad where you don''t speak the language, or never leave your country again?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Live abroad', 0), ('Never leave', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Would you rather lose all your photos, or all your messages?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('All my photos', 0), ('All my messages', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Cilantro/coriander?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Love it', 0), ('It''s fine', 1), ('Tastes like soap', 2)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Best part of the day?', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Early morning', 0), ('Afternoon', 1), ('Evening', 2), ('Late night', 3)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Vote where you think the fewest people will vote.', NULL, 'approval_rating', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('Left', 0), ('Right', 1)) AS o(option_text, sort_order);

WITH q AS (
  INSERT INTO questions (prompt, description, type, country_code,
    targeting_type, nsfw, is_hidden, is_private, author_id, is_seeded)
  VALUES ('Pick the option you think most people will pick.', NULL, 'multiple_choice', 'US', 'globe', false, false, false, NULL, true)
  RETURNING id
)
INSERT INTO question_options (question_id, option_text, sort_order)
SELECT q.id, o.option_text, o.sort_order
FROM q, (VALUES ('🔴', 0), ('🔵', 1), ('🟢', 2), ('🟡', 3)) AS o(option_text, sort_order);

COMMIT;
